public enum TokenType {
    NUMBER, IDENTIFIER, STRING,

    PLUS, MINUS, MULTIPLY, DIVIDE,
    LPAREN, RPAREN, IF, ELSE, AND, OR,
    PRINT, EQUALS, COMMA, DEF, CLASS,
    INDENT, DEDENT, NEWLINE, GREATER, LESS,
    GREATER_EQUAL, LESS_EQUAL, NOT, NOTEQUAL,
    RETURN, DOT, EQUAL_EQUAL, TRUE, FALSE,
    FOR, WHILE, IN, LBRACKET, RBRACKET,
    COLON,
    EOF
}